### ISSUE TITLE
Input path does not exist

### ISSUE THREAD

**Issue by kdatta** [ldbc-dev/ldbc_snb_datagen_deprecated2015#18]
Hi,

I cloned the "master" branch and tag "v0.1.2" of the ldbc data generator and ran the run.sh script. Somehow it is unable to find required files which are not mentioned anywhere in the documentation.

Here's the prints from the run.sh:
[kdatta1@localworkstation:~/workspace/ldbc/ldbc_snb_datagen]$ ./run.sh 
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building ldbc_socialnet_dbgen 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ldbc_socialnet_dbgen ---
[INFO] Deleting /home/kdatta1/workspace/ldbc/ldbc_snb_datagen/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.246 s
[INFO] Finished at: 2014-10-15T12:21:21-05:00
[INFO] Final Memory: 15M/963M
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building ldbc_socialnet_dbgen 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-assembly-plugin:2.4:assembly (default-cli) @ ldbc_socialnet_dbgen >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ldbc_socialnet_dbgen ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 255 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ ldbc_socialnet_dbgen ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 102 source files to /home/kdatta1/workspace/ldbc/ldbc_snb_datagen/target/classes
[WARNING] /home/kdatta1/workspace/ldbc/ldbc_snb_datagen/src/main/java/ldbc/socialnet/dbgen/generator/ScalableGenerator.java: Some input files use unchecked or unsafe operations.
[WARNING] /home/kdatta1/workspace/ldbc/ldbc_snb_datagen/src/main/java/ldbc/socialnet/dbgen/generator/ScalableGenerator.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ ldbc_socialnet_dbgen ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/kdatta1/workspace/ldbc/ldbc_snb_datagen/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ ldbc_socialnet_dbgen ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ ldbc_socialnet_dbgen ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ ldbc_socialnet_dbgen ---
[INFO] Building jar: /home/kdatta1/workspace/ldbc/ldbc_snb_datagen/target/ldbc_socialnet_dbgen-0.1.jar
[INFO] 
[INFO] <<< maven-assembly-plugin:2.4:assembly (default-cli) @ ldbc_socialnet_dbgen <<<
[INFO] 
[INFO] --- maven-assembly-plugin:2.4:assembly (default-cli) @ ldbc_socialnet_dbgen ---
[INFO] Building jar: /home/kdatta1/workspace/ldbc/ldbc_snb_datagen/target/ldbc_socialnet_dbgen.jar
[WARNING] Configuration options: 'appendAssemblyId' is set to false, and 'classifier' is missing.
Instead of attaching the assembly file: /home/kdatta1/workspace/ldbc/ldbc_snb_datagen/target/ldbc_socialnet_dbgen.jar, it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[WARNING] Replacing pre-existing project main-artifact file: /home/kdatta1/workspace/ldbc/ldbc_snb_datagen/target/ldbc_socialnet_dbgen-0.1.jar
with assembly file: /home/kdatta1/workspace/ldbc/ldbc_snb_datagen/target/ldbc_socialnet_dbgen.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.545 s
[INFO] Finished at: 2014-10-15T12:21:45-05:00
[INFO] Final Memory: 62M/1720M
[INFO] ------------------------------------------------------------------------
********\* Configuration *********
scaleFactor: 30
numThreads: 4
serializer: csv
compressed: false
updateStreams: false
outputDir: hdfs://localworkstation:19010/user/kdatta1/

---

NUMBER OF THREADS 4

---
- Starting: Person generation and friendship generation 1 *
  ************************************************
  14/10/15 12:21:48 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
  14/10/15 12:21:49 INFO input.FileInputFormat: Total input paths to process : 1
  14/10/15 12:21:49 INFO mapred.JobClient: Running job: job_201410131716_0073
  14/10/15 12:21:50 INFO mapred.JobClient:  map 0% reduce 0%
  14/10/15 12:21:50 INFO mapred.JobClient: Job complete: job_201410131716_0073
  14/10/15 12:21:50 INFO mapred.JobClient: Counters: 0
  ************************************************
- Starting: Sorting by first dimension *
  ************************************************
  14/10/15 12:21:50 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
  14/10/15 12:21:50 INFO input.FileInputFormat: Total input paths to process : 0
  14/10/15 12:21:51 INFO mapred.JobClient: Running job: job_201410131716_0074
  14/10/15 12:21:52 INFO mapred.JobClient:  map 0% reduce 0%
  14/10/15 12:21:52 INFO mapred.JobClient: Job complete: job_201410131716_0074
  14/10/15 12:21:52 INFO mapred.JobClient: Counters: 0
  ************************************************
- Starting: Friendship generation 2. *
  ************************************************
  14/10/15 12:21:52 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
  14/10/15 12:21:52 INFO input.FileInputFormat: Total input paths to process : 0
  14/10/15 12:21:52 INFO mapred.JobClient: Running job: job_201410131716_0075
  14/10/15 12:21:53 INFO mapred.JobClient:  map 0% reduce 0%
  14/10/15 12:21:53 INFO mapred.JobClient: Job complete: job_201410131716_0075
  14/10/15 12:21:53 INFO mapred.JobClient: Counters: 0
  ************************************************
- Starting: Sorting by second dimension *
  ************************************************
  14/10/15 12:21:53 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
  14/10/15 12:21:54 INFO input.FileInputFormat: Total input paths to process : 0
  14/10/15 12:21:54 INFO mapred.JobClient: Running job: job_201410131716_0076
  14/10/15 12:21:55 INFO mapred.JobClient:  map 0% reduce 0%
  14/10/15 12:21:55 INFO mapred.JobClient: Job complete: job_201410131716_0076
  14/10/15 12:21:55 INFO mapred.JobClient: Counters: 0
  ************************************************
- Starting: Friendship generation 3. *
  ************************************************
  14/10/15 12:21:55 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
  14/10/15 12:21:56 INFO input.FileInputFormat: Total input paths to process : 0
  14/10/15 12:21:57 INFO mapred.JobClient: Running job: job_201410131716_0077
  14/10/15 12:21:58 INFO mapred.JobClient:  map 0% reduce 0%
  14/10/15 12:21:58 INFO mapred.JobClient: Job complete: job_201410131716_0077
  14/10/15 12:21:58 INFO mapred.JobClient: Counters: 0
  ************************************************
- Starting: Sorting by third dimension *
  ************************************************
  14/10/15 12:21:58 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
  14/10/15 12:21:58 INFO input.FileInputFormat: Total input paths to process : 0
  14/10/15 12:21:59 INFO mapred.JobClient: Running job: job_201410131716_0078
  14/10/15 12:22:00 INFO mapred.JobClient:  map 0% reduce 0%
  14/10/15 12:22:00 INFO mapred.JobClient: Job complete: job_201410131716_0078
  14/10/15 12:22:00 INFO mapred.JobClient: Counters: 0
  ************************************************
- Starting: Generating person activity *
  ************************************************
  14/10/15 12:22:00 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
  14/10/15 12:22:00 INFO input.FileInputFormat: Total input paths to process : 0
  14/10/15 12:22:00 INFO mapred.JobClient: Running job: job_201410131716_0079
  14/10/15 12:22:01 INFO mapred.JobClient:  map 0% reduce 0%
  14/10/15 12:22:01 INFO mapred.JobClient: Job complete: job_201410131716_0079
  14/10/15 12:22:01 INFO mapred.JobClient: Counters: 0
  ************************************************
- Starting: Sorting update streams *
  ************************************************
  14/10/15 12:22:01 WARN mapred.JobClient: Use GenericOptionsParser for parsing the arguments. Applications should implement Tool for the same.
  14/10/15 12:22:02 INFO mapred.JobClient: Cleaning up the staging area hdfs://localworkstation:19010/home/kdatta1/Hdfs/hadoop-datastore/tmp/mapred/staging/kdatta1/.staging/job_201410131716_0080
  14/10/15 12:22:02 ERROR security.UserGroupInformation: PriviledgedActionException as:kdatta1 cause:org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input path does not exist: hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_0.csv
  Input path does not exist: hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_1.csv
  Input path does not exist: hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_2.csv
  Input path does not exist: hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_3.csv
  Exception in thread "main" org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input path does not exist: hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_0.csv
  Input path does not exist: hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_1.csv
  Input path does not exist: hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_2.csv
  Input path does not exist: hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_3.csv
  at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:235)
  at org.apache.hadoop.mapreduce.lib.input.SequenceFileInputFormat.listStatus(SequenceFileInputFormat.java:55)
  at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:252)
  at org.apache.hadoop.mapred.JobClient.writeNewSplits(JobClient.java:1054)
  at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1071)
  at org.apache.hadoop.mapred.JobClient.access$700(JobClient.java:179)
  at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:983)
  at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:936)
  at java.security.AccessController.doPrivileged(Native Method)
  at javax.security.auth.Subject.doAs(Subject.java:415)
  at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
  at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:936)
  at org.apache.hadoop.mapreduce.Job.submit(Job.java:550)
  at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:580)
  at ldbc.socialnet.dbgen.generator.MRGenerateUsers.runGenerateJob(MRGenerateUsers.java:557)
  at ldbc.socialnet.dbgen.generator.MRGenerateUsers.main(MRGenerateUsers.java:594)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.apache.hadoop.util.RunJar.main(RunJar.java:160)
  Traceback (most recent call last):
  File "paramgenerator/generateparams.py", line 3, in <module>
    import readfactors
  File "/home/kdatta1/workspace/ldbc/ldbc_snb_datagen/paramgenerator/readfactors.py", line 7
    FACTOR_MAP = {value: key for (key, value) in enumerate(FACTORS)}
                               ^
  SyntaxError: invalid syntax
  [kdatta1@localworkstation:~/workspace/ldbc/ldbc_snb_datagen]$

**Comment by kdatta** [comment]
Found the fix. I was running with Hadoop-1.2.1. I ran the generator on Hadoop-2.3.0 and it worked. I think this should be mentioned in the README or documentation

**Comment by ArnauPrat** [comment]
Hi @kdatta 
The files it is looking for are temporary files DATAGEN is using to store some data.
Does the output you pasted here the same regardless of the version you use? Let's focus on the latest version in the master branch from now on. 
Can you check if the following files:

hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_0.csv
hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_1.csv
hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_2.csv
hdfs://localworkstation:19010/user/kdatta1/social_network/temp_updateStream_3.csv

exist in your hadoop file system after the crash?

**Comment by ArnauPrat** [comment]
Wow, you just found a fix! Btw, we do not officially support hadoop 2.3.0, it should work using 1.2.1. In any case, this is good news that DATAGEN works with 2.3.0.

**Comment by kdatta** [comment]
If it should work with 1.2.1, I should reopen the issue, because it doesn't.
