### ISSUE TITLE
python problems

### ISSUE THREAD

**Issue by awolven** [ldbc-dev/ldbc_snb_datagen_deprecated2015#27]
I'm trying to get a fully functional version of python to run run.sh, but python 2.6.6 encountered a syntax error and python 2.7.9 installation seems to be faulty in that it cannot find necessary modules.  I followed the python installation instructions but am still having problems:

'import site' failed; use -v for traceback^M
Traceback (most recent call last):^M
  File "paramgenerator/generateparams.py", line 2, in <module>^M
    import discoverparams^M
  File "/disk1/awolven/ldbc_socialnet_bm/paramgenerator/discoverparams.py", line 2, in <module>^M
    import getopt^M
ImportError: No module named getopt^M

**Comment by minhducit** [comment]
Hi awolven, 

Have you searched for some solutions e.g., 
http://james.wheare.org/notes/2009/02/import-site-failed-use-v-for-traceback.php

and 
https://github.com/carlhuda/janus/issues/305

May be, it can help.
