### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by Gillani0** [ldbc-dev/ldbc_snb_datagen_deprecated2015#28]
Hi, I am getting the following error when I tried to generate data with numOfPerson and numOfyeah option in params.init.  Cheers

"loading input for parameter generation
find parameter bindings for Persons
Traceback (most recent call last):
  File "paramgenerator/generateparams.py", line 296, in <module>
    sys.exit(main())
  File "paramgenerator/generateparams.py", line 152, in main
    selectedPersonParams[i] = discoverparams.generate(factors)
  File "/home/ubuntu/snbDatagen/ldbc_snb_datagen-master/paramgenerator/discoverparams.py", line 129, in generate
    current_windows = findWindows(factors,paramId,amount,(0,len(factors)));
  File "/home/ubuntu/snbDatagen/ldbc_snb_datagen-master/paramgenerator/discoverparams.py", line 54, in findWindows
    initWindow.avg = getAverageCost(data[start:amount], itemgetter(param))
  File "/home/ubuntu/snbDatagen/ldbc_snb_datagen-master/paramgenerator/discoverparams.py", line 37, in getAverageCost
    return float(sum([key(r) for r in rows])) / len(rows)
ZeroDivisionError: float division by zero"

**Comment by ArnauPrat** [comment]
Hi @Gillani0 
The version of datagen you are using is currently deprecated. It was moved from the public ldbc group to the ldbc-dev group some weeks ago. Please got to https://github.com/ldbc/ldbc_snb_datagen and clone that repository. Read the documentation again, as it now uses hadoop 2.6.0 and the format of params file has changed.
Regards,
Arnau
