### ISSUE TITLE
Python error in paramgenerator scripts?

### ISSUE THREAD

**Issue by wileeam** [ldbc-dev/ldbc_snb_datagen_deprecated2015#6]
Hello,

 the new code in the script run.sh about param generation causes an error (see below) at the end of the generation process of the dataset...
The generation of the dataset is completed successfully though

``` python
14/06/02 10:19:29 INFO mapred.JobClient:     Map output records=1000
309 total seconds
Warning: $HADOOP_HOME is deprecated.

Warning: $HADOOP_HOME is deprecated.

loading input for parameter generation
find parameter bindings for Persons
find parameter bindings for Countries
find parameter bindings for Tags
find parameter bindings for Timestamps
Traceback (most recent call last):
  File "paramgenerator/generateparams.py", line 216, in <module>
    sys.exit(main())
  File "paramgenerator/generateparams.py", line 164, in main
    selectedTimeParams = findTimeParams(timeSelectionInput, argv[1], argv[2], ts[1])
  File "/NOBACKUP/ldbc_socialnet_bm/ldbc_socialnet_dbgen/paramgenerator/timeparameters.py", line 201, in findTimeParams
    output[queryId] = findTimeParameters(input[queryId][0], mycFactors, input[queryId][1], input[queryId][2])
  File "/NOBACKUP/ldbc_socialnet_bm/ldbc_socialnet_dbgen/paramgenerator/timeparameters.py", line 33, in findTimeParameters
    timeParams = timestampSelection(factors,medians)
  File "/NOBACKUP/ldbc_socialnet_bm/ldbc_socialnet_dbgen/paramgenerator/timeparameters.py", line 66, in getTimeParamsWithMedian
    if currentMedian.count > median:
AttributeError: 'int' object has no attribute 'count'
```

**Comment by agubichev** [comment]
Hello,
can you tell what is the scaleFactor that you are using?

**Comment by wileeam** [comment]
Hi!

 our own... see below:

``` python
    <scale_factor number="2" >
        <num_persons>1000</num_persons>
        <start_year>2014</start_year>
        <num_years>10</num_years>
    </scale_factor>
```

I haven't tried setting this parameters directly as it was possible before. Awaiting further information just in case.

**Comment by agubichev** [comment]
i pushed the fix, can you try it now?

**Comment by ArnauPrat** [comment]
btw, I have improved the way parameters are passed to the DBGEN. Here you
are the new instructions:

https://github.com/ldbc/ldbc_socialnet_bm/wiki/Compilation_Execution

Arnau

2014-06-02 13:23 GMT+02:00 agubichev notifications@github.com:

**Comment by wileeam** [comment]
Now... float division by zero for the same parameters as before...

``` bash
4/06/02 16:11:14 INFO mapred.JobClient:     Map output records=1000
309 total seconds
14/06/02 16:11:14 INFO util.NativeCodeLoader: Loaded the native-hadoop library
loading input for parameter generation
find parameter bindings for Persons
find parameter bindings for Countries
find parameter bindings for Tags
find parameter bindings for Timestamps
Traceback (most recent call last):
  File "paramgenerator/generateparams.py", line 216, in <module>
    sys.exit(main())
  File "paramgenerator/generateparams.py", line 164, in main
    selectedTimeParams = findTimeParams(timeSelectionInput, argv[1], argv[2], ts[1])
  File "/NOBACKUP/ldbc_socialnet_bm/ldbc_socialnet_dbgen/paramgenerator/timeparameters.py", line 205, in findTimeParams
    output[queryId] = findTimeParameters(input[queryId][0], mycFactors, input[queryId][1], input[queryId][2])
  File "/NOBACKUP/ldbc_socialnet_bm/ldbc_socialnet_dbgen/paramgenerator/timeparameters.py", line 31, in findTimeParameters
    timeParams = timestampSelection(factors,medians)
  File "/NOBACKUP/ldbc_socialnet_bm/ldbc_socialnet_dbgen/paramgenerator/timeparameters.py", line 74, in getTimeParamsWithMedian
    duration = int(28*median/currentMedian.count)
ZeroDivisionError: float division by zero
```

**Comment by ArnauPrat** [comment]
Hi Guillermo, 

Thank you for reporting these issues. In any case, these errors do not 
affect the generation of the social network, since they are from a post 
process to generate substitution parameters for the LDBC-SNB. 
Therefore, if you are interested only on the social network generated, 
the output files should still be correct.

Regards,

Arnau.

**Comment by agubichev** [comment]
Should be fixed for now, but I assume you do not use parameters anyways. Their generation can be disabled by setting PARAM_GENERATION to 0 in run.sh

**Comment by wileeam** [comment]
Correct! No errors now! Thanks @ArnauPrat and @agubichev 
I was aware that the dataset was generated without errors but thought about letting you know about this.

Closing this issue :) Now the inconsistency test comes...
